name: map
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  get: ^4.6.6
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
